language: go
go:
  - 1.10
env:
  global:
    - HUGO_VERSION=0.37

# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Install hugo
before_install:
  - mkdir -p bin
  - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    -o bin/hugo.tar.gz
  - tar xzvvf bin/hugo.tar.gz -C ./bin

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - cd src
  - "../bin/hugo"
  - echo 'www.pauldamora.com' > public/CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
