baseurl = "https://pmdamora.github.io/"
languageCode = "en-US"
title = "Paul D'Amora"
theme = "paul"
pluralizelisttitles = "false"
disqusShortname = "pauldamora"
googleAnalytics = "UA-106776049-1"


[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Paul D'Amora"

[params.social]
  Github        = "pmdamora"
  Email         = "pmdamora@gmail.com"
  LinkedIn      = "pmdamora"
  Instagram     = "pmdamora"

[taxonomies]
  trips = "trips"
  tripsdesc = "tripsdesc"

## Main Menu
[[menu.main]]
  name = "writings"
  weight = 100
  identifier = "writings"
  url = "/writings/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "hiking"
  identifier = "hiking"
  weight = 300
  url = "/hiking/"
[[menu.main]]
  name = "highpoints"
  identifier = "highpoints"
  parent = "hiking"
  weight = 300
  url = "/hiking/highpoints"
[[menu.main]]
  name = "résumé"
  identifier = "resume"
  weight = 400
  url = "/resume.pdf"
# [[menu.main]]
#   name = "contact"
#   identifier = "contact"
#   weight = 500
#   url = "/contact"
