baseurl = "http://www.pauldamora.com/"
languageCode = "en-US"
title = "Paul D'Amora"
theme = "paul"
pluralizelisttitles = "false"

disqusShortname = "pauldamora"
googleAnalytics = "UA-106776049-1"


[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile2.jpg"
  author = "Paul D'Amora"
  tagline = "I'm <strong>Paul D'Amora</strong>, a Software Developer <br /> <span class='amp'>&amp;</span> Adventurer."

[params.social]
  Github        = "pmdamora"
  Email         = "pmdamora@gmail.com"
  LinkedIn      = "pmdamora"
  Instagram     = "pmdamora"

[taxonomies]
  trips = "trips"
  tripsdesc = "tripsdesc"

## Main Menu
[[menu.main]]
  name = "writings"
  weight = 100
  identifier = "writings"
  url = "/writings/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "hiking"
  identifier = "hiking"
  weight = 300
  url = "/hiking/"
# [[menu.main]]
#   name = "highpoints"
#   identifier = "highpoints"
#   parent = "hiking"
#   weight = 300
#   url = "/hiking/highpoints"
[[menu.main]]
  name = "résumé"
  identifier = "resume"
  weight = 400
  url = "/documents/resume.pdf"

  ## Text Descriptions
  [params.text]
    highpoints = "<a href='http://highpointers.org/'>U.S. Highpointing</a> refers to ascending to the natural point with the highest elevation in each of the 50 U.S. states. I hope to someday reach the top of every state, and will document my progress on the map below."
    projects = "Some of my recent work and projects can be found in their entirety on my <a href='https://github.com/pmdamora'>Github page</a>. Additionally, a select few of my projects are detailed below."
    hiking = "All of my major hiking (and related) trips are listed below in reverse chronological order. Click through to view my trail journal and/or more details about the trip."
